version: '3'

services:
  api:
    container_name: api
    build: .
    volumes:
      - .:/app
    ports:
      - 4000:8080
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - 5432:5432
    env_file:
      - ./database/env
